from fastapi.testclient import TestClient
from app.api import app

client = TestClient(app)

def test_read_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "Bonjour, vous êtes bien sur l'application de scoring, hébergée sur Heroku. "
                                          "Cette API permet de prédire la probabilité de défaut de paiement pour un client "
                                          "en fonction de ses caractéristiques. Envoyez une requête POST à /predict pour obtenir une prédiction."}

def test_predict():
    # Exemple de données client
    client_data = {
        "Taux_Paiement": 0.02,
        "Score_Externe_2": 0.5,
        "Score_Externe_3": 0.6,
        "Jours_Depuis_Naissance": -12000,
        "Montant_Annuite": 25000.0,
        "Somme_Paiements": 150000.0,
        "Moyenne_Paiements_Precedents": 10.0,
        "Montant_Credit": 200000.0,
        "Moyenne_Jours_Retard_Paiements": 0.0,
        "Moyenne_Paiements_Approuves": 12.0,
        "Prix_Biens": 180000.0,
        "Jours_Depuis_Publication_ID": -4000,
        "Jours_Emploi": -2000,
        "Max_Jours_Credit_Bureau": -3000.0,
        "Taille_Solde_Mensuel_POS": 6.0,
        "Max_Jours_Entree_Paiement": -30.0,
        "Jours_Dernier_Changement_Telephone": -2000.0,
        "Montant_Min_Paiement": 5000.0,
        "Max_Jours_Fin_Credit_Bureau": -1000.0,
        "Moyenne_Jours_Entree_Paiement": -15.0,
        "Moyenne_Credit_Dette_Bureau": 50000.0,
        "Moyenne_Annuite_Approuvee": 10000.0,
        "Moyenne_Diff_Paiement": 2000.0,
        "Moyenne_Contrats_Refuses": 0.1,
        "Pourcentage_Jours_Emploi": 0.7,
        "Moyenne_Combinaison_Produits_CashXSelllow": 0.1,
        "Max_Paiement": 25000.0,
        "Somme_Total_Credit_Bureau": 300000.0,
        "Pourcentage_Annuite_Revenu": 0.2,
        "Max_Versement_Initial": 0.0,
        "Pourcentage_Revenu_Credit": 0.5,
        "Somme_Jours_Entree_Paiement": -300.0,
        "Min_Credit_Applications_Precedentes": 0.9,
        "Type_Contrat_Pretes_Espece": False,
        "Evaluation_Regionale_Client_Ville": 2,
        "Type_Occupation_Chauffeurs": False,
        "Niveau_Education_Superieur": False,
        "Moyenne_Credit_Bureau_Hypotheque": 0.0,
        "Somme_Paiements_Approuves": 36.0,
        "Jours_Depuis_Enregistrement": -4500.0,
        "Moyenne_DPD_Defaut_POS": 0.0,
        "Somme_Solde_Mensuel_Bureau_Credit": 20.0,
        "Moyenne_Rendement_Precedent_Eleve": 0.1,
        "Moyenne_Rendement_Precedent_Faible": 0.2,
        "Pourcentage_Max_Credit_Approuve": 0.9,
        "Population_Relative_Region": 0.02,
        "Moyenne_Pourcentage_Credit_Applications_Precedentes": 0.7,
        "Nombre_Versions_Echeancier_Installation": 1.0,
        "Somme_Limites_Credit_Bureau": 10000.0,
        "Max_Credit_Bureau": 50000.0,
        "Max_Jours_Retard_Paiements_Installation": 0.0,
        "Statut_Familial_Marie": False,
        "Moyenne_Type_Paiement_Precedent_XNA": 0.0,
        "Moyenne_Jours_Credit_Bureau": -3000.0,
        "Indicateur_Possession_Voiture": 0,
        "Moyenne_Type_Credit_Bureau_Microcredit": 0.0,
        "Max_Jours_Decision_Approuvee": -10.0,
        "Somme_Dettes_Credit_Bureau": 200000.0,
        "Moyenne_Pourcentage_Paiement_Installation": 0.5,
        "Moyenne_Type_Client_Precedent_Nouveau": 0.0,
        "Moyenne_Montant_Paiement": 20000.0,
        "Moyenne_Credit_Retard_Bureau": 0.0,
        "Moyenne_Jours_Retard_Paiements_Installation": 0.0,
        "Moyenne_Credit_Bureau": 20000.0,
        "Revenu_Par_Personne": 5000.0,
        "Moyenne_Jours_Fin_Credit_Bureau": -1500.0,
        "Nombre_Demandes_Credit_Bureau_Trimestre": 0.0,
        "Somme_Differences_Paiement": 1000.0,
        "Moyenne_Credits_Actifs_Bureau": 0.9,
        "Moyenne_Solde_Mensuel_POS": 0.0,
        "Somme_Paiements_Precedents": 60.0,
        "Min_Jours_Decision_Precedents": -500.0,
        "Moyenne_Jours_Decision_Precedents": -200.0,
        "Somme_Jours_Retard_Paiements_Installation": 0.0,
        "Moyenne_Combinaison_Produits_CashStreetlow": 0.0,
        "Max_Annuite_Approuvee": 30000.0,
        "Max_Credit_Approuve": 150000.0,
        "Moyenne_Categorie_Biens_Precedente_Meubles": 0.1,
        "Heure_Debut_Processus_Approbaton": 10,
        "Type_Occupation_Ouvriers": False,
        "Min_Demande_Approuvee": 10000.0,
        "Moyenne_Statut_Contrat_POS_Actif": 0.8,
        "Moyenne_Combinaison_Produits_POS_Industrie": 0.1,
        "Moyenne_Statut_Contrat_POS_Complet": 0.1,
        "Type_Revenu_Travailleur": False,
        "Moyenne_Categorie_Biens_Precedente_XNA": 0.0,
        "Nombre_Defauts_Sociaux_60Jours": 0.0,
        "Indicateur_Document_3": 1,
        "Min_Credit_Approuve": 0.0,
        "Min_Annuite_Precedente": 0.0,
        "Max_Jours_Retard_Paiements_Installation": 0.0,
        "Difference_Max_Paiement": 0.0,
        "Nombre_Defauts_Sociaux_30Jours": 0.0,
        "Moyenne_Type_Credit_Bureau_Pret_Automobile": 0.0,
        "Max_DPD_Defaut_POS": 0.0,
        "Heure_Max_Debut_Processus_Approbaton": 0.0,
        "Type_Organisation_Construction": False,
        "Moyenne_Type_Canal_Precedent_Ventes_Entreprise": 0.0
    }
    
    response = client.post("/predict", json=client_data)
    assert response.status_code == 200
    assert "prediction" in response.json()
    assert "probability" in response.json()
